apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pagamento-deployment
spec:
  template:
    metadata:
      name: app-pagamento
      labels:
        app: app-pagamento
    spec:
      containers:
        - name: app-container
          image: gabccardoso/pagamento:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1000m
  replicas: 3
  selector:
    matchLabels:
      app: app-pagamento